mkdir filmes
cd filmes
mkdir acao
mkdir comedia
mkdir suspense
touch filmes.txt
touch suspense/o_llamado.txt
touch acao/os_vingadores.txt
touch acao/iron_man.txt
touch comedia/se_eu_fosse_voce.txt
touch comedia/the_hangover.txt
