---
tags: []
layout: input_bottom
editor: 0
type: interactive
extra_visible: false
manual_evaluation: false
choices: []
goal: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  kind: last_query_outputs
  output: |-
    se_eu_fosse_voce.txt
    the_hangover.txt
name: Mudando de Diretório
