---
tags: []
layout: input_bottom
editor: 0
type: interactive
extra_visible: false
manual_evaluation: false
choices: []
goal: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  kind: query_passes
  query: cd /home/mumuki/curriculum && git status
name: Criando um repositorio
