---
tags: []
layout: input_bottom
editor: 0
type: interactive
extra_visible: false
manual_evaluation: false
choices: []
goal: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  kind: last_query_equals
  value: git remote add origin http://outro-computador/foo/bar
name: Associando ao repositório remoto
