mkdir escritos
cd escritos
mkdir drama
mkdir comedia
mkdir suspense
touch ni_el_tiro_del_final.txt
touch suspense/el_farmer.txt
touch drama/ficciones.txt
touch drama/el_libro_de_los_seres_imaginarios.txt
touch comedia/el_bar_del_infierno.txt
touch comedia/el_angel_gris.txt
