---
tags: []
layout: input_bottom
editor: 0
type: interactive
extra_visible: false
manual_evaluation: false
choices: []
goal: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  kind: last_query_outputs
  output: |-
    el_angel_gris.txt
    el_bar_del_infierno.txt
name: Cambiando de Directorio
